---
title: "CorrigeDataCamp"
output: html_document
date: "2026-04-17"
---

```{r setup, include=FALSE}
rm(list = ls())

unzip("2025-26 Tractament de les dades Gr.A-T (36423)-Tarea Intermediate R(Datacamp)-3281647.zip",
      exdir = "entregas_descomprimidas")
```

```{r}
ficheros <- list.files("entregas_descomprimidas", pattern = "\\.txt$", recursive = TRUE, full.names = TRUE)
```

```{r}
ficheros_puntos <- ficheros[grep("puntos", ficheros, ignore.case = TRUE)]
```

```{r}
apellidos <- c()
puntos <- c()
NomFile <- c()
Puntos <- c()

for (i in 1:length(ficheros_puntos)) {
  
  ruta <- ficheros_puntos[i]
  
  partes <- strsplit(ruta, "/")[[1]]
  carpeta <- partes[length(partes) - 1]
  nombre <- strsplit(carpeta, "_")[[1]][1]
  apellido <- strsplit(nombre, ",")[[1]][1]
  
  contenido <- readLines(ruta)
  texto <- paste(contenido, collapse = " ")
  
  apellidos <- c(apellidos, trimws(apellido))
  puntos <- c(puntos, as.numeric(texto))
  NomFile <- c(NomFile, partes[length(partes)])
  Puntos <- c(Puntos, texto)
}
```

```{r}
df <- data.frame(
  apellidos,
  puntos,
  NomFile,
  Puntos,
  stringsAsFactors = FALSE
)

df <- df[order(df$apellidos), ]
```

```{r}
library(openxlsx)

write.xlsx(df, "NotasRIntermedio.xlsx", overwrite = TRUE)
```

```{r}
library(readxl)

alumnos <- read_excel("AlumnosTD25_26.xlsx")
alumnos <- as.data.frame(alumnos)

alumnos$clave <- paste(alumnos$`Apellido(s)`, alumnos$Nombre, sep = ", ")


df$clave <- paste(df$apellidos)


resultado <- merge(alumnos, df, by = "clave", all.x = TRUE)
```

```{r}
write.xlsx(resultado, "AlumnosNotas.xlsx", overwrite = TRUE)
```